### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by lilbaj** [lilbaj/accessibility-fixer-upper#1]
@muxlowc
I have been working on this assignment for the last two days and I'm stuck at 13% for my 320p screenshot. I am really not sure what I'm missing, especially cause some of my other classmates I've talked to have been able to get below 12%. I have tried bolding everything to try to make it match the weight of the screenshot and that didn't even work. I have no clue what to do next. 

<img width="316" alt="Screen Shot 2020-04-03 at 1 20 06 PM" src="https://user-images.githubusercontent.com/55108804/78388104-71123780-75ae-11ea-9843-01c993aa9814.png">
<img width="568" alt="Screen Shot 2020-04-03 at 1 19 18 PM" src="https://user-images.githubusercontent.com/55108804/78388114-740d2800-75ae-11ea-97c4-6f73078a2892.png">

**Comment by muxlowc** [comment]
@lilbaj hey so this one is a bit weird and even the solution doesn't pass markbot because the screenshot is a bit old - no worries, I'll go in and give you the mark manually :)

**Comment by lilbaj** [comment]
Oh okay, thank you so much! :)
